apiVersion: v1
kind: Pod
metadata:
  name: kaniko-pulse-build
  namespace: holm
spec:
  nodeSelector:
    kubernetes.io/hostname: openmediavault
  restartPolicy: Never
  initContainers:
    - name: prepare-workspace
      image: busybox
      command:
        - /bin/sh
        - -c
        - |
          cp /source/* /workspace/
          chmod 644 /workspace/*
          ls -la /workspace/
          cat /workspace/go.mod
      volumeMounts:
        - name: source
          mountPath: /source
        - name: workspace
          mountPath: /workspace
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=/workspace/Dockerfile"
        - "--context=/workspace"
        - "--destination=registry.holm.svc.cluster.local:5000/pulse:latest"
        - "--insecure"
        - "--skip-tls-verify"
      volumeMounts:
        - name: workspace
          mountPath: /workspace
  volumes:
    - name: source
      configMap:
        name: pulse-source
    - name: workspace
      emptyDir: {}
