apiVersion: apps/v1
kind: Deployment
metadata:
  name: pxe-server
  namespace: holm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pxe-server
  template:
    metadata:
      labels:
        app: pxe-server
    spec:
      # Must use host network for DHCP/TFTP to work
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - rpi-1
      containers:
      - name: pxe-server
        image: 192.168.8.197:31500/pxe-server:latest
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_BIND_SERVICE
        ports:
        - containerPort: 67
          protocol: UDP
          hostPort: 67
        - containerPort: 69
          protocol: UDP
          hostPort: 69
        - containerPort: 80
          protocol: TCP
          hostPort: 8088
        - containerPort: 8080
          protocol: TCP
          hostPort: 30669
        env:
        - name: PORT
          value: "8080"
        - name: SERVER_IP
          value: "192.168.8.197"
        - name: TFTP_ROOT
          value: "/tftpboot"
        - name: HTTP_ROOT
          value: "/var/www/html"
        - name: ISO_DIR
          value: "/iso"
        volumeMounts:
        - name: tftpboot
          mountPath: /tftpboot
        - name: www
          mountPath: /var/www/html
        - name: iso
          mountPath: /iso
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: tftpboot
        hostPath:
          path: /opt/pxe/tftpboot
          type: DirectoryOrCreate
      - name: www
        hostPath:
          path: /opt/pxe/www
          type: DirectoryOrCreate
      - name: iso
        hostPath:
          path: /opt/pxe/iso
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: pxe-server
  namespace: holm
spec:
  type: ClusterIP
  selector:
    app: pxe-server
  ports:
  - name: api
    port: 8080
    targetPort: 8080
  - name: http
    port: 80
    targetPort: 80
  - name: tftp
    port: 69
    targetPort: 69
    protocol: UDP
  - name: dhcp
    port: 67
    targetPort: 67
    protocol: UDP
